#!/usr/bin/env -S uv run
# /// script
# dependencies = []
# ///
"""
Create bootstrap size manifest from density report estimates.

This script bridges density reports (with estimated_pack_size_mb) to the
size manifest format required by pack-planner. Use this for the initial
planning pass before any packs are built.

For accurate sizes after building, use create_size_manifest.py instead.

Workflow:
1. Run partition_by_boundary.py --discover-only to get boundary cells
2. Run convert_discovery_to_density_report.py to create density report
3. Run this script to create bootstrap size manifest
4. Run pack-planner with --size-manifest
5. Build packs
6. (Optional) Re-run with create_size_manifest.py for refined sizes

Usage:
    uv run create_bootstrap_size_manifest.py \
        --density-report /Volumes/Lightroom/ebird_partitioned/density_report_res4.json \
        --output /Volumes/Lightroom/ebird_partitioned/size_manifest.json
"""

import argparse
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(
        description="Create bootstrap size manifest from density report estimates"
    )
    parser.add_argument(
        "--density-report",
        type=Path,
        required=True,
        help="Density report JSON file (from convert_discovery_to_density_report.py)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output path for bootstrap size manifest JSON",
    )

    args = parser.parse_args()

    if not args.density_report.exists():
        print(f"Error: Density report not found: {args.density_report}")
        return 1

    print(f"Loading density report from: {args.density_report}")
    with open(args.density_report) as f:
        report = json.load(f)

    cells = []
    total_size_mb = 0

    for cell in report.get("cells", []):
        # Use estimated_pack_size_mb from density report
        # This field is generated by convert_discovery_to_density_report.py
        estimated_size = cell.get("estimated_pack_size_mb", 0.5)

        cells.append(
            {
                "boundary_cell": cell["h3_cell"],
                "size_mb": estimated_size,
                "source_region": "bootstrap",  # Mark as estimated, not measured
            }
        )
        total_size_mb += estimated_size

    # Build output matching the format expected by pack-planner
    output = {
        "version": "1.0",
        "description": "Bootstrap size manifest from density estimates (not actual builds)",
        "bootstrap": True,  # Flag indicating this is estimated, not measured
        "stats": {
            "total_cells": len(cells),
            "total_size_mb": round(total_size_mb, 2),
            "average_size_mb_per_cell": round(total_size_mb / len(cells), 4)
            if cells
            else 0,
        },
        "cells": cells,
    }

    # Write output
    print(f"Writing bootstrap size manifest to: {args.output}")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w") as f:
        json.dump(output, f, indent=2)

    print()
    print("=" * 60)
    print("BOOTSTRAP SIZE MANIFEST CREATED")
    print("=" * 60)
    print(f"  Cells: {len(cells):,}")
    print(f"  Estimated total: {total_size_mb:.1f} MB ({total_size_mb / 1024:.2f} GB)")
    print(
        f"  Average per cell: {total_size_mb / len(cells):.4f} MB"
        if cells
        else "  Average per cell: N/A"
    )
    print(f"  Output: {args.output}")
    print()
    print("NOTE: This is a bootstrap manifest using estimated sizes.")
    print("For accurate sizes, build packs first, then use create_size_manifest.py")

    return 0


if __name__ == "__main__":
    exit(main())
